# Generated by Django 3.2.20 on 2023-08-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('title1', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards/', verbose_name='image')),
            ],
        ),
        migrations.AlterField(
            model_name='tanit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tanit/', verbose_name='image'),
        ),
    ]
