# Generated by Django 3.2.20 on 2023-08-16 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ders', '0003_hakkimda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hakkimda',
        ),
    ]
